### ISSUE TITLE
后端 god 模块（2 周内）

### ISSUE THREAD

**Issue by NiceKingWei** [NiceKingWei/krad#18]

**Comment by NiceKingWei** [comment]
1. 在 GodHelper 里定义输入和输出的 case class，分别为 Msgxxx 和 Resxxx。例如:
  case class MsgChooseHero(sid:Int,hero:String)
  case class ResChooseHero(count:Int,result:String)

2. 在 MyJsonProtocol 里声明隐式变量，例如：
  implicit val RequestGameFormat = jsonFormat2(RequestGame)
  implicit val ResChooseHeroFormat = jsonFormat2(ResChooseHero)

3. 在 GodHelper 里写 get 和 to 函数，例如
  def getChooseHero(str:String):MsgChooseHero = {
    str.parseJson.convertTo[MsgChooseHero]
  }

  def toChooseHero(count:Int,result:String):String = {
    ResChooseHero(count,result).toJson.toString
  }

**Comment by Ignoramus0817** [comment]
Finished.
