### ISSUE TITLE
GambleChecker 和 PlayerChecker改动

### ISSUE THREAD

**Issue by Ignoramus0817** [NiceKingWei/krad#20]
游戏设计改动后,GambleChecker 和 PlayerChecker需要进行一定的改动。
//cards{strategy,skills}
//least energy consume = 4
//energyLim = cardNumLimit = healthPoint

**Comment by JoanZS** [comment]
Player类里面需要增加一个SID的属性，表示对应到的人

**Comment by Ignoramus0817** [comment]
cards system finished, not tested yet.

**Comment by Ignoramus0817** [comment]
Cards system finished, all tests passed.
