### ISSUE TITLE
God的异步（2 周内）

### ISSUE THREAD

**Issue by JoanZS** [NiceKingWei/krad#25]
游戏开始时，God被实例化（获得SID数组）。
God中要有一个request(int SID, string   msg)函数来：获得玩家(sid)消息，理解msg，并根据其内容调用god的其它函数，获得需要返回的结果string，（并送回前端->NiceKingWei）。
request调用的god的其它函数，如果需要改变God中数据，则需要使用synchronized(同步)。如果需要等待：调用wait。等待：例如需要等待其他玩家操作，但不能用while(1)忙等=>在所有玩家都可以进下一步的时候使用notifyAll来唤醒其它等待中的线程。

**Comment by NiceKingWei** [comment]
http://www.importnew.com/16453.html
